print("SARAAA IS DUMB AS FUCCKKKKK")

print("SARAAA IS DUMB AS FUCCKKKKK")

print("SARAAA IS DUMB AS FUCCKKKKK")

print("SARAAA IS DUMB AS FUCCKKKKK")
print("SARAAA IS DUMB AS FUCCKKKKK")
print("SARAAA IS DUMB AS FUCCKKKKK")

print("SARAAA IS DUMB AS FUCCKKKKK")
print("SARAAA IS DUMB AS FUCCKKKKK")
print("SARAAA IS DUMB AS FUCCKKKKK")
print("SARAAA IS DUMB AS FUCCKKKKK")
print("SARAAA IS DUMB AS FUCCKKKKK")

print("SARAAA IS DUMB AS FUCCKKKKK")
print("SARAAA IS DUMB AS FUCCKKKKK")
print("SARAAA IS DUMB AS FUCCKKKKK")
print("SARAAA IS DUMB AS FUCCKKKKK")
print("SARAAA IS DUMB AS FUCCKKKKK")